Emacs

diff --git a/confmerge b/confmerge
--- a/confmerge
+++ b/confmerge
@@ -34,6 +34,11 @@ dosudo () {
 }
 
 cmerge () {
+  if [[ -n "${3:+x}" ]]; then
+    echo "Error: cmerge() requires 2 parameters, got 3: $1, $2, $3"
+    exit 1
+  fi
+
   SRC="$1"                              # source
   HSRC="$SRC.$HNAME"                    # host-specific source
   DST="$2"                              # destination
@@ -114,7 +119,7 @@ cmerge gtk/bookmarks                       ~/.config/gtk-3.0/bookmarks
 
 cmerge emacs/init.el                       ~/.config/emacs/init
 cmerge emacs/early-init.el                 ~/.config/emacs/early-init.el
-cmerge emacs/rust-analyzer.el              ~/.config/emacs/extra/rust-analyzer.el
+cmerge emacs/lsp-rust.el                   ~/.config/emacs/elpa/lsp-mode-*/lsp-rust.el
 
 cmerge bash/rc                             ~/.bashrc
 cmerge bash/rc_graalvm                     ~/.bashrc_graalvm
