Updates

diff --git a/scripts/chdpi b/scripts/chdpi
--- a/scripts/chdpi
+++ b/scripts/chdpi
@@ -13,9 +13,7 @@ if [ "$1" = "hi" ] || [ "$1" = "high" ]; then
 
   sed -i 's/^# export GDK_SCALE/export GDK_SCALE/'         ~/.profile
   sed -i 's/^# export GDK_DPI_SCALE/export GDK_DPI_SCALE/' ~/.profile
-fi
-
-if [ "$1" = "lo" ] || [ "$1" = "low" ]; then
+elif [ "$1" = "lo" ] || [ "$1" = "low" ]; then
   xfconf-query -c xsettings -p /Xft/DPI                 -s 96
   xfconf-query -c xsettings -p /Gtk/CursorThemeSize     -s 16
   xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1
@@ -23,6 +21,9 @@ if [ "$1" = "lo" ] || [ "$1" = "low" ]; then
 
   sed -i 's/^export GDK_SCALE/# export GDK_SCALE/'         ~/.profile
   sed -i 's/^export GDK_DPI_SCALE/# export GDK_DPI_SCALE/' ~/.profile
+else
+  echo "Error: Only accept 'high' or 'low'"
+  exit 1
 fi
 
 loginctl terminate-session "$XDG_SESSION_ID"
diff --git a/scripts/chvga b/scripts/chvga
--- a/scripts/chvga
+++ b/scripts/chvga
@@ -7,10 +7,11 @@ set -o nounset
 
 if [ "$1" = "intel" ] || [ "$1" = "in" ]; then
   optimus-manager --switch intel
-fi
-
-if [ "$1" = "nvidia" ] || [ "$1" = "nv" ]; then
+elif [ "$1" = "nvidia" ] || [ "$1" = "nv" ]; then
   optimus-manager --switch nvidia
+else
+  echo "Error: Only accept 'nvidia' or 'intel'"
+  exit 1
 fi
 
 loginctl terminate-session "$XDG_SESSION_ID"
